/**
 * Platform Verification Script
 * Generated by platform-maker
 *
 * Runs comprehensive checks to verify the platform is working.
 * Usage: npx tsx scripts/verify.ts
 */

import { spawn, ChildProcess } from 'child_process';

const SERVER_URL = 'http://localhost:3001';
const STARTUP_TIMEOUT = 10000;
const CHECK_INTERVAL = 500;

interface TestResult {
  name: string;
  passed: boolean;
  status?: number;
  error?: string;
}

async function waitForServer(url: string, timeout: number): Promise<boolean> {
  const start = Date.now();

  while (Date.now() - start < timeout) {
    try {
      const response = await fetch(`${url}/api/health`);
      if (response.ok) {
        const data = await response.json();
        if (data.status === 'ok') return true;
      }
    } catch {
      // Server not ready yet
    }
    await new Promise(r => setTimeout(r, CHECK_INTERVAL));
  }

  return false;
}

async function testEndpoint(path: string): Promise<{ ok: boolean; status: number }> {
  try {
    const response = await fetch(`${SERVER_URL}${path}`);
    return { ok: response.ok, status: response.status };
  } catch (error) {
    return { ok: false, status: 0 };
  }
}

async function runTypeCheck(): Promise<TestResult> {
  return new Promise((resolve) => {
    const proc = spawn('pnpm', ['check'], { stdio: 'pipe' });
    let stderr = '';

    proc.stderr?.on('data', (data) => {
      stderr += data.toString();
    });

    proc.on('close', (code) => {
      resolve({
        name: 'TypeScript check',
        passed: code === 0,
        error: code !== 0 ? stderr.slice(0, 500) : undefined
      });
    });
  });
}

async function runBuild(): Promise<TestResult> {
  return new Promise((resolve) => {
    const proc = spawn('pnpm', ['build'], { stdio: 'pipe' });
    let stderr = '';

    proc.stderr?.on('data', (data) => {
      stderr += data.toString();
    });

    proc.on('close', (code) => {
      resolve({
        name: 'Build',
        passed: code === 0,
        error: code !== 0 ? stderr.slice(0, 500) : undefined
      });
    });
  });
}

async function main() {
  console.log('Starting platform verification...\n');

  const results: TestResult[] = [];

  // Step 1: TypeScript check
  console.log('Running TypeScript check...');
  const typeCheckResult = await runTypeCheck();
  results.push(typeCheckResult);
  console.log(typeCheckResult.passed ? '  ✓ TypeScript check passed' : `  ✗ TypeScript check failed`);

  if (!typeCheckResult.passed) {
    console.log('\nTypeScript errors must be fixed before continuing.');
    if (typeCheckResult.error) {
      console.log('\nError preview:');
      console.log(typeCheckResult.error);
    }
    process.exit(1);
  }

  // Step 2: Build check
  console.log('\nRunning build...');
  const buildResult = await runBuild();
  results.push(buildResult);
  console.log(buildResult.passed ? '  ✓ Build succeeded' : '  ✗ Build failed');

  if (!buildResult.passed) {
    console.log('\nBuild errors must be fixed before continuing.');
    if (buildResult.error) {
      console.log('\nError preview:');
      console.log(buildResult.error);
    }
    process.exit(1);
  }

  // Step 3: Start server and run endpoint tests
  console.log('\nStarting server...');

  const server = spawn('pnpm', ['dev:server'], {
    stdio: ['ignore', 'pipe', 'pipe'],
    detached: true,
  });

  const serverPid = server.pid;

  try {
    // Wait for server
    console.log('Waiting for server to be ready...');
    const serverReady = await waitForServer(SERVER_URL, STARTUP_TIMEOUT);

    if (!serverReady) {
      results.push({
        name: 'Server startup',
        passed: false,
        error: 'Server failed to start within timeout'
      });
      console.log('  ✗ Server failed to start');
    } else {
      results.push({
        name: 'Server startup',
        passed: true
      });
      console.log('  ✓ Server is ready\n');

      // Run endpoint tests
      const endpointTests = [
        { name: 'Health check', path: '/api/health' },
        { name: 'tRPC endpoint', path: '/trpc' },
      ];

      console.log('Testing endpoints:');
      for (const test of endpointTests) {
        const result = await testEndpoint(test.path);
        // 401 is acceptable - means endpoint exists but needs auth
        // 404 on /trpc is expected (needs specific procedure)
        const passed = result.ok || result.status === 401 || (test.path === '/trpc' && result.status === 404);
        results.push({
          name: test.name,
          passed,
          status: result.status
        });
        console.log(passed ? `  ✓ ${test.name}` : `  ✗ ${test.name} (status: ${result.status})`);
      }
    }
  } finally {
    // Cleanup - kill server process group
    if (serverPid) {
      try {
        process.kill(-serverPid, 'SIGTERM');
      } catch {
        // Process may have already exited
      }
    }
  }

  // Summary
  console.log('\n' + '═'.repeat(50));
  const passed = results.filter(r => r.passed).length;
  const failed = results.filter(r => !r.passed).length;

  console.log(`Results: ${passed} passed, ${failed} failed\n`);

  for (const result of results) {
    const icon = result.passed ? '✓' : '✗';
    console.log(`  ${icon} ${result.name}`);
  }

  if (failed > 0) {
    console.log('\n' + '═'.repeat(50));
    console.log('Verification FAILED');
    console.log('\nFailed checks:');
    for (const result of results.filter(r => !r.passed)) {
      console.log(`  - ${result.name}${result.error ? `: ${result.error}` : ''}`);
    }
    process.exit(1);
  }

  console.log('\n' + '═'.repeat(50));
  console.log('Verification PASSED');
  console.log('═'.repeat(50));
}

main().catch(error => {
  console.error('Verification script error:', error.message);
  process.exit(1);
});
